a = int(input("Enter a number: "))
b = a
print("Largest: " + str(b))
a = int(input("Enter a number: "))
b = max(a,b)
print("Largest: " + str(b))
a = int(input("Enter a number: "))
b = max(a,b)
print("Largest: " + str(b))
a = int(input("Enter a number: "))
b = max(a,b)
print("Largest: " + str(b))
a = int(input("Enter a number: "))
b = max(a,b)
print("Largest: " + str(b))
a = int(input("Enter a number: "))
b = max(a,b)
print("Largest: " + str(b))
